apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-proj
  labels:
    app: mlops-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-proj
  template:
    metadata:
      labels:
        app: mlops-proj
    spec:
      containers:
      - name: mlops-proj
        image: 020866158197.dkr.ecr.ap-south-1.amazonaws.com/mlops-proj:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: TEST_ENV
          valueFrom:
            secretKeyRef:
              name: test_env
              key: TEST_ENV

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-proj-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-proj
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000